<?xml version="1.0" encoding="utf-8"?><Database Name="eGrocery" Class="SampleDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=SANJOG;Initial Catalog=eGrocery;Integrated Security=True" SettingsObjectName="WCFTest.Properties.Settings" SettingsPropertyName="eGroceryConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Product1" Member="Product1s">
    <Type Name="Product1">
      <Column Name="ProductId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Descr" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SKU" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="QtyRecieved" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QtyRem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DateReceived" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
</Database>